#!/usr/bin/env bash
# Rejoicing on Every Side — Sunday Build-Out helper (2026-09-13)
# Run from anywhere:  ~/StayTheWay/teachings/rejoicing/sunday-buildout.sh {status|deploy|verify|commit|all}
#
# The landing page (index.html) is GENERATED by teachings/_build/gen.py — don't hand-edit it.
# Nav / featured-card / homepage "This Week" edits are WordPress files and are done per-week
# (see REJOICING_MASTER_PROMPTS.md and the weekly package memory); this script covers the
# static package, the .htaccess rewrite, verification, and git.

set -euo pipefail

SLUG="rejoicing"
TAG="rejoicing-sunday-2026-09-13"
ROOT="$HOME/StayTheWay/teachings/${SLUG}"
SSH_KEY="$HOME/.ssh/siteground_stw"
SSH_PORT=18765
SSH_USER="u2121-p9x72lgphszm"
SSH_HOST="ssh.staytheway.com"
DOCROOT="/home/customer/www/staytheway.com/public_html"
REMOTE_DIR="${DOCROOT}/stw-teachings/${SLUG}"
SITE="https://staytheway.com/teachings/${SLUG}"

PAGES=(index.html bingo.html quiz.html prayer.html kids-quiz.html kids-bingo.html kids-activity.html qr-codes.html)

rsh() { ssh -i "$SSH_KEY" -p "$SSH_PORT" -o ConnectTimeout=20 "${SSH_USER}@${SSH_HOST}" "$@"; }

cmd_status() {
  echo "=== Build status — $(date '+%Y-%m-%d %H:%M:%S') ==="
  cd "$ROOT"
  for f in "${PAGES[@]}" kids/index.html qr/qr-landing.png qr/qr-prayer.png qr/qr-bingo.png qr/qr-quiz.png \
           qr/qr-kids.png qr/qr-subscribe.png qr/qr-podcast.png \
           REJOICING_MASTER_PROMPTS.md youtube-description.md kids-teacher-guide.md kids-worship-song.md \
           slides/StayTheWay_The_Reset_VERT_18-slide.pptx slides/Rejoicing-on-Every-Side_27-slide.pptx \
           Sunday-Reset-Rejoicing-on-Every-Side.md; do
    if [ -f "$f" ]; then
      printf "  [OK]   %-46s (%s bytes)\n" "$f" "$(wc -c < "$f" | tr -d ' ')"
    else
      printf "  [MISS] %s\n" "$f"
    fi
  done
}

cmd_deploy() {
  echo "=== Deploying ${SLUG}/ to SiteGround ==="
  cd "$ROOT"
  rsh "mkdir -p '${REMOTE_DIR}/qr'"
  scp -i "$SSH_KEY" -P "$SSH_PORT" "${PAGES[@]}" "${SSH_USER}@${SSH_HOST}:${REMOTE_DIR}/"
  scp -i "$SSH_KEY" -P "$SSH_PORT" qr/*.png qr/*.svg "${SSH_USER}@${SSH_HOST}:${REMOTE_DIR}/qr/"
  # The Joy Trail lives in its own folder — never add kids/index.html to PAGES (flat scp would overwrite the landing page)
  rsh "mkdir -p '${REMOTE_DIR}/kids'"
  scp -i "$SSH_KEY" -P "$SSH_PORT" kids/index.html "${SSH_USER}@${SSH_HOST}:${REMOTE_DIR}/kids/"

  echo "=== .htaccess rewrite (idempotent, backs up first) ==="
  rsh bash -s -- "$SLUG" "$DOCROOT" <<'REMOTE'
set -e
SLUG="$1"; cd "$2"
if grep -qF "RewriteRule ^teachings/${SLUG}/\$ " .htaccess; then
  echo "  rewrite already present"
else
  cp -p .htaccess ".htaccess.bak-${SLUG}"
  awk -v s="$SLUG" '/^# END StayTheWay Teachings Rewrite/{
      print "RewriteRule ^teachings/" s "/$ /stw-teachings/" s "/index.html [L]";
      print "RewriteRule ^teachings/" s "/(.*)$ /stw-teachings/" s "/$1 [L]" } {print}' .htaccess > .htaccess.tmp
  mv .htaccess.tmp .htaccess
  echo "  rewrite added (backup: .htaccess.bak-${SLUG})"
fi
grep -n "teachings/${SLUG}" .htaccess
wp cache flush --path="$2" >/dev/null 2>&1 && echo "  wp object cache flushed" || true
REMOTE
  echo "NOTE: WP-rendered pages (/teachings/, homepage) sit behind SiteGround Dynamic Cache."
  echo "      Flush it in Site Tools -> Speed -> Caching -> Flush Cache."
}

cmd_verify() {
  echo "=== Verifying live URLs (cache-busted) ==="
  local cb; cb=$(date +%s); local fail=0
  for p in "" "${PAGES[@]:1}" kids/ qr/qr-landing.png; do
    local url="${SITE}/${p}"
    local out; out=$(curl -s -o /dev/null -w "%{http_code} %{size_download}" "${url}?cb=${cb}")
    printf "  %-8s %s\n" "$out" "$url"
    [[ "$out" == 200* ]] || fail=1
  done
  return $fail
}

cmd_commit() {
  cd "$HOME/StayTheWay"
  git add "teachings/${SLUG}/" teachings/_build/
  git commit -m "Add Rejoicing on Every Side teaching package (Psalm 65 / Proverbs 13)" || true
  git push origin main
  git rev-parse "$TAG" >/dev/null 2>&1 || git tag "$TAG"
  git push origin "$TAG"
}

case "${1:-status}" in
  status)  cmd_status ;;
  deploy)  cmd_deploy ;;
  verify)  cmd_verify ;;
  commit)  cmd_commit ;;
  all)     cmd_status && cmd_deploy && cmd_verify && cmd_commit ;;
  *) echo "Usage: $0 {status|deploy|verify|commit|all}" ; exit 1 ;;
esac
